language: cpp

jobs:
    include:
      - os: linux
        sudo: false
        dist: bionic
        name: "Linux X11"
        addons:
            apt:
                packages:
                    - libx11-dev

      - os: linux
        sudo: false
        dist: bionic
        name: "Linux Wayland"
        addons:
            apt:
                packages:
                    - libwayland-dev
        env:
          - USE_WAYLAND=ON

      - os: osx
        sudo: false
        name: "MacOS X Cocoa"

      - os: osx
        sudo: false
        name: "MacOS X Metal"
        env:
          - USE_METAL_API=ON

      - os: osx
        sudo: false
        name: "MacOS iOS"
        env:
          - USE_IOS=ON

script:
  - mkdir build
  - cd build
  - echo "Config"
  - if [ $TRAVIS_OS_NAME = 'osx' ]; then
      if test -n "${USE_IOS}"; then
        cmake .. -G Xcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 ;
      elif test -n "${USE_METAL_API}"; then
        cmake .. -USE_METAL_API=ON;
      else
        cmake ..;
      fi
    else
      if test -n "${USE_WAYLAND}"; then
        cmake .. -DUSE_WAYLAND=ON;
      else
        cmake ..;
      fi
    fi
  - echo "Build"
  - if test -n "${USE_IOS}"; then
      cmake --build . --target minifb ;
    else
      cmake --build . ;
    fi
