language: cpp

matrix:
    include:
      - os: linux
        sudo: false
        dist: bionic
        sudo: false
        name: "Linux X11"
        addons:
            apt:
                packages:
                    - libx11-dev

      - os: linux
        sudo: false
        dist: bionic
        sudo: false
        name: "Linux Wayland"
        addons:
            apt:
                packages:
                    - libwayland-dev
        env:
          - USE_WAYLAND=ON

      - os: osx
        sudo: false
        name: "MacOS X Cocoa"

      - os: osx
        sudo: false
        name: "MacOS X Metal"
        env:
          - USE_METAL_API=ON

script:
  - mkdir build
  - cd build
  - if [ $TRAVIS_OS_NAME = 'osx' ]; then
      if test -n "${USE_METAL_API}"; then
        cmake .. -USE_METAL_API=ON;
      else
        cmake ..;
      fi
    else
      if test -n "${USE_WAYLAND}"; then
        cmake .. -DUSE_WAYLAND=ON;
      else
        cmake ..;
      fi
    fi
  - cmake --build .
  