language: cpp

matrix:
    include:
      - os: linux
        dist: bionic
        sudo: false
        name: "Linux X11"
        addons:
            apt:
                packages:
                    - libx11-dev
      - os: linux
        dist: bionic
        sudo: false
        name: "Linux Wayland"
        addons:
            apt:
                packages:
                    - libwayland-dev
        env:
          - USE_WAYLAND=ON

script:
  - mkdir build
  - cd build
  - if test -n "${USE_WAYLAND}"; then
      cmake .. -DUSE_WAYLAND=ON
    else
      cmake ..
    fi
  - cmake --build .
  